# -*- coding: utf-8 -*-
"""Tugas 1 Praktikum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFbZLnkAeNrQeIDMket9U3yMUCk_vP2T
"""

Menu = ["Kopi Susu","Matcha Latte","Americano"]
harga = [18000, 22000, 15000]
jumlah = [4, 3, 5]

sub_kopi_susu = jumlah[0] * harga[0]
sub_Matcha = jumlah[1] * harga[1]
sub_americano = jumlah[2] * harga[2]

subtotal_pendapatan = sub_kopi_susu + sub_Matcha + sub_americano


biaya_operasional = 15000
total_barang = jumlah[0] + jumlah[1] + jumlah[2]
pendapatan_bersih = subtotal_pendapatan - biaya_operasional
target_tercapai = (subtotal_pendapatan > 200000) and (total_barang > 10)

print(subtotal_pendapatan)
print(pendapatan_bersih)
print(target_tercapai)